# Generated by Django 4.2.6 on 2023-10-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_address_alter_user_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='db_users',
        ),
    ]
